source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
platform :ios, '7.0'

#target 'ZCamera_Example', :exclusive => true do
pod 'MWPhotoBrowser', '2.1.1'
pod 'ZComponent', :subspecs => ['ZMacro','Category','ZBaseViewController']
    #end

